@url = http://localhost:3000
@jsonContent = content-type: application/json

###
GET {{url}}
{{jsonContent}}

###
POST {{url}}/create-account
{{jsonContent}}

{
    "email": "gabrielbissey",
    "firstName": "Gabriel",
    "lastName": "Bissey",
    "phoneNumber": "555-555-5555",
    "supporter": true
}

###
GET {{url}}/user?email=gabrielbissey@gmail.com